name: Parent Workflow

on:
  push:
    branches: [ "master" ]
  workflow_call:

jobs:
  parent-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1 from Parent Repository
        uses: actions/checkout@v3
      - name: Job 2 from Parent Repository
        env:
          USER: ${{ secrets.AUSER }}
          PASS: ${{ secrets.APASS }}
      - name: Job 3 from Parent Repository
        run: | 
          echo "USER=${{ secrets.AUSER }}" >> $GITHUB_ENV        
          echo "PASS=${{ secrets.APASS }}" >> $GITHUB_ENV
          echo "${{env.USER}}"
          echo "${{env.PASS}}"
      - name: Job 4 Set up secret file
        run: |
          echo ${{ secrets.AUSER }} | sed 's/./& /g'
