name: Parent Workflow

on:
  push:
    branches: [ "master" ]
  workflow_call:

jobs:
  parent-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1 from Parent Repository
        uses: actions/checkout@v3
      - name: Job 2 from Parent Repository
        with:
          AZURE_USERNAME: ${{ secrets.AUSER }}
          AZURE_PASSWORD: ${{ secrets.APASS }}
      - name: Job 3 from Parent Repository
        run: echo "$AZURE_USERNAME"
      - name: Job 4 from Parent Repository
        run: echo $AZURE_USERNAME
