name: Parent Workflow

on:
  push:
    branches: [ "master" ]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Fetching Secrets from Github Secrets
        with: 
          variable: ${{ secrets.PASSWORD }}

      - name: Printing Secrets from Github Secrets
        run: |
          Stored secret is: "$variable"
