name: Parent Workflow

on:
  push:
    branches: [ "master" ]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Print Secret Variable
        env:
          SECRET_VAR: ${{ secrets.PASSWORD }}
        run: echo $SECRET_VAR
