name: Parent Workflow

on:
  push:
    branches: [ "master" ]
  workflow_call:

jobs:
  build:
      env:
        variable: ${{ secrets.PASSWORD }}
      runs-on: ubuntu-latest
      steps:
        - name: Fetching Secrets from Github Secrets
          uses: actions/checkout@v3
          with: 
            variable: ${{ secrets.PASSWORD }}

        - name: Printing Secrets from Github Secrets
          run: echo ${{env.variable}}
