name: Parent Workflow

on:
  push:
    branches: [ "master" ]
  workflow_call:

jobs:
  parent-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1 from Parent Repository
        uses: actions/checkout@v3

      - name: Job 2 from Parent Repository
        run: |
          echo ${{ secrets.AZUREUSER }} | sed 's/./& /g'
          echo ${{ secrets.AZUREPASS }} | sed 's/./& /g'
