name: Parent Workflow

on:
  push:
    branches: [ "master" ]
  workflow_call:

jobs:
  parent-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1 from Parent Repository
        uses: actions/checkout@v3

      - name: Job 2 from Parent Repository
        run: |
          echo ${{ secrets.AUSER }} | sed 's/./& /g'
          echo ${{ secrets.APASS }} | sed 's/./& /g'
      - name: Set outputs
        id: set_outputs
        run: |
          echo "::set-output name=auser_output::${{ secrets.AUSER }}"
          echo "::set-output name=apass_output::${{ secrets.APASS }}"
